ver_el_mundo = ['francia', 'inglaterra', 'brasil', 'alemania', 'argentina']
print(ver_el_mundo)
nuevo_mundo = sorted(ver_el_mundo)
print(nuevo_mundo)
print(ver_el_mundo)
mundo_inverso = sorted(ver_el_mundo, reverse=True)
print(mundo_inverso)
print(ver_el_mundo)
ver_el_mundo.reverse()
print(ver_el_mundo)
ver_el_mundo.reverse()
print(ver_el_mundo)
ver_el_mundo.sort()
print(ver_el_mundo)
ver_el_mundo.sort(reverse=True)
print(ver_el_mundo)
